"""Addes fields in client

Revision ID: 233641ae3c45
Revises: 2630cbb343da
Create Date: 2024-11-07 09:37:21.461102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '233641ae3c45'
down_revision = '2630cbb343da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vat', sa.String(length=15), nullable=False, server_default=""))
        batch_op.add_column(sa.Column('address', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('mol', sa.String(length=100), nullable=False, server_default=""))

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.alter_column('client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'client', ['client_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'client', ['client_id'], ['id'])
        batch_op.alter_column('client_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('mol')
        batch_op.drop_column('address')
        batch_op.drop_column('vat')

    # ### end Alembic commands ###
