"""Recreate database schema

Revision ID: 2630cbb343da
Revises: 
Create Date: 2024-11-01 12:53:47.970989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2630cbb343da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_account', schema=None) as batch_op:
        batch_op.drop_column('bic')
        batch_op.drop_column('account_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_number', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('bic', sa.VARCHAR(length=11), nullable=False))

    # ### end Alembic commands ###
