"""Added MaintenanceOffer model for manually entered assets in offers

Revision ID: 2ebd1f3bbd74
Revises: 3cb641dada62
Create Date: 2024-11-10 16:29:46.688824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ebd1f3bbd74'
down_revision = '3cb641dada62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('validity_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_offer_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maintenance_offer_id', sa.Integer(), nullable=False),
    sa.Column('asset_type_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_type_id'], ['asset_type.id'], ),
    sa.ForeignKeyConstraint(['maintenance_offer_id'], ['maintenance_offers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('offer_assets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offer_assets',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('offer_id', sa.INTEGER(), nullable=False),
    sa.Column('asset_type_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['asset_type_id'], ['asset_type.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('maintenance_offer_assets')
    op.drop_table('maintenance_offers')
    # ### end Alembic commands ###
