"""Asset delete

Revision ID: 4ae5e50d1e2c
Revises: 2ebd1f3bbd74
Create Date: 2024-11-10 18:56:08.921782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ae5e50d1e2c'
down_revision = '2ebd1f3bbd74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asset')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('client_id', sa.INTEGER(), nullable=False),
    sa.Column('employee_id', sa.INTEGER(), nullable=True),
    sa.Column('type_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('serial_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('purchase_date', sa.DATE(), nullable=True),
    sa.Column('warranty_expiration', sa.DATE(), nullable=True),
    sa.Column('notes', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['asset_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
